name = "video-service"
type = "javascript"
account_id = "107f550b334bbef92303090ba5ce56ae"
workers_dev = true
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
node_compat = true
nodejs_compat = true

[build]
command = "npm install && npx prisma generate && npm run build"
[build.upload]
format = "service-worker"

[vars]
NODE_ENV = "production"
DATABASE_URL = "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDY2NmQyMmItMzJkZC00ZWZjLWIyMjUtNjdmODM4OTc4NmFhIiwidGVuYW50X2lkIjoiNGRjN2QzYTJlNjJlMDNjODJmZDlmOWMzOWM5ZDY0MGNlNjRlODQ4ZmFlYzgwZDM5MDY1NmFjYjMxNjZjNDE0OSIsImludGVybmFsX3NlY3JldCI6IjZhMWYwNDJhLWRjMDMtNDZiOS05MTVlLTdiMTJmMTQxNzk5NyJ9.quK7JHymJKPx8SJ3rKjtNc2AboHhIoNUjhPtS-Opcgc"

[env.production]
vars = { ENVIRONMENT = "production" }

[[r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "gradestack"
preview_bucket_name = "gradestack-dev"

[miniflare]
node_compat = true
