name = "video-service"
main = "dist/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
node_compat = true

[build]
command = "npm install && npm run prisma:generate && npm run build"

[vars]
NODE_ENV = "production"

pages_build_output_dir = "dist"

[env.production]
vars = { 
  NODE_ENV = "production",
  ENVIRONMENT = "production"
}

# Cấu hình R2 cho môi trường production
[[env.production.r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "gradestack"
preview_bucket_name = "gradestack-dev"
