name = "video-service"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[site]
bucket = "./dist"
pages_build_output_dir = "dist"

[env.production.var]
NODE_ENV = "production"
ENVIRONMENT = "production"
NODE_VERSION = "20.2"


[[r2_buckets]]
bucket_name = "gradestack"
preview_bucket_name = "gradestack-dev"