name = "video-service"
type = "javascript"
account_id = "107f550b334bbef92303090ba5ce56ae"
workers_dev = true
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
node_compat = true
nodejs_compat = true

[build]
command = "node --version && npm install && npx prisma generate && npm run build"
[build.upload]
format = "service-worker"

[vars]
NODE_ENV = "production"
NODE_VERSION = "20.2.0"
[env.production]
vars = { ENVIRONMENT = "production" }

[[r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "gradestack"
preview_bucket_name = "gradestack-dev"

[miniflare]
node_compat = true
