name = "video-service"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[site]
bucket = "./dist"
pages_build_output_dir = "dist"

[env.production]
vars = { NODE_ENV = "production", ENVIRONMENT = "production" }

[[r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "gradestack"
preview_bucket_name = "gradestack-dev"
